### ISSUE TITLE
Absolutely nothing can be copied, absolutely nothing can be marked - http://zelka.org/details.php?id=439221

### ISSUE THREAD

**Issue by Rusenche** [lcandy2/Select-like-a-Boss#4]
Hello developer of this extension.

I didn't know until recently that the extension has a new version and that this new version is available at https://chrome.google.com/webstore/detail/select-like-a-boss/mbnnmpmcijodolgeejegcijdamonganh/ - Select like a Boss
2022 May - Version 2022.5.

I installed it but ran into a problem with this new version at http://zelka.org/details.php?id=439221. Yes, registration is required to check and fix the problem.

I am attaching a photo: https://i.postimg.cc/MKsbjCt1/1.png

What is the problem? No row can be selected from the one marked in the picture. Absolutely nothing can be copied, absolutely nothing can be marked.

I still have Select like a Boss 2015.4.24 - when I activate it - everything works - can highlight the text, can copy the text or part of it.

Please take a look at the new version - Select like a Boss 2022 May - Version 2022.5 and fix it to work for this site as well.

Thanks.

**Comment by Rusenche** [comment]
I installed the new version.

But it doesn't work quite right. If an attempt is made to copy here is this in the picture:

it is supposed to be highlighted, but immediately the highlighted text is dropped/unselected. So I try 8 times and it still fails to flag. After refreshing the page - after a few more tagging attempts - the tagging is successful.

Even if this site has a tagging ban - the very old extension with a version from 8 years ago successfully works (`Select like a Boss 2015.4.24`), while the version from an hour ago (**19.07.2023** - I specify this because my topic is from 9 months ago ) does not work well.

I hope you can check my signal and according to the picture look around and experiment that it doesn't get the successful marking even from the eighth time.

I found a flaw with your new version - while posting a comment in the box - it doesn't allow me to mark/select my own text (I haven't posted it yet).

I also noticed another problem. If https://translate.google.com/ is opened and text for translation is written - you cannot mark your own text.

The new version needs fixes.

**Comment by lcandy2** [comment]
For translate.google.com, it's already fixed in version 2023 Jul 33 and just needs to wait for the Google Store to clear it.

For the issue you mentioned with websites not being selectable, the extension was rewritten in 2022 May to perform the same function in a non-intrusive way - meaning that the extension will not interfere with the original functionality of the webpage, and at the same time have better compatibility with other extensions or more websites.
In this way, the site's original anti-copy feature works as it should, and you may need to find some additional usersrcipt to make it selectable

Thanks for using!

**Comment by Rusenche** [comment]
@lcandy2 

Will you post a fix here: https://github.com/lcandy2/Select-like-a-Boss/releases?!

Have you checked the problem when writing a comment here in the comment box (but before that comment is published) that one cannot select one's own written text?!

**Comment by Rusenche** [comment]
@lcandy2

I confirm that with the new version https://github.com/lcandy2/Select-like-a-Boss/releases/tag/2023.7.42 some issues with google translate and with github have been resolved successfully.

But now absolutely nothing can be selected from the text of http://zelka.org/details.php?id=439221.

And as far as I understand from your comments here - once the site has disallowed selecting/copying text, your extension should intentionally not work.

**Comment by Rusenche** [comment]
I'm confused as to what the purpose of this extension is.

`Select like a Boss is a browser extension that allows you to easily select link text just like regular text, making it easier to copy. With this extension, you can quickly select and copy link text without the hassle of selecting the surrounding elements.`

In practice, the function of this extension is to mark, select and be able to copy text.

That may have been the original idea.

At the moment it is not.

As far as I understood - "not to break the original functionality of a site"... But isn't this extension for users or is it for sites?! This extension is supposed to help users, but it turns out that this extension doesn't help users, it helps sites.

I'm really confused.

If a site has a ban on copying, selecting and marking text - that's why this extension should be - allow all the listed functions.

On the contrary - if a given site does not prohibit copying, selecting and marking text - then why do we need this extension, as we can freely do the listed three operations?!

After the problem with http://zelka.org/details.php?id=439221 was solved yesterday by another site - it is now possible to copy, select and mark text - then why do I need this extension, when with the normal functions of Chromium-based browsers I can do all this?!

I'm really confused and I don't understand what the function of this extension is, protecting the bans of the sites from not being able to copy, select, etc., well, then it turns out that in both cases this extension is not used.

**Comment by lcandy2** [comment]
> Select like a Boss is a browser extension that allows you to easily select link text just like regular text, making it easier to copy. With this extension, you can quickly select and copy link text without the hassle of selecting the surrounding elements.

As you said, this extension is build to select and copy LINK text without doing anything else.

The original implementation is that when the mouse is pressed left or right, the extension selects the text (including links) that the cursor passes over instead of my mouse, which creates a lot of incompatibilities.

Now, the newest, most efficient, and best compatible implementation is that when the mouse is pressed left or right, the text attribute on the object (link, button) which the mouse is pressed on is changed to be selectable, just like normal text, and when the mouse is released or pressed up or down, everything is restored, which is much more compatible, and much more efficient.

I could certainly easily add an exception for the zelka.org site to solve the problem you're encountering, but there are many more sites that are using anti-copying practices that I can't take into consideration. I'd rather suggest you go to greasyfork.org and look for the anti-anti-copying userscripts, cause they build for anti-anti-copying (which this extension isn't, it's just for selecting the links), and you'll have a much better user experience using them as well.

**Comment by Rusenche** [comment]
To my delight - I removed the current version because it does not serve the logical purposes it should serve.

My user experience has actually improved, staying on the faithful and time tested wonderful version `Select like a Boss 2015.4.24`. As I wrote above - the extension should be for the benefit of the user, not for the benefit of the sites!
